### ISSUE TITLE
Problem con Yith Points and Rewards

### ISSUE THREAD

**Issue by Carangelo** [LDAV/woocommerce-pdf-italian-add-on#17]
Buongiorno,

sto riscontrando un problema di compatibilità con il plugin in oggetto di Yith ([https://yithemes.com/themes/plugins/yith-woocommerce-points-and-rewards/](https://yithemes.com/themes/plugins/yith-woocommerce-points-and-rewards/)):

il plugin Yith crea dei coupon sulla base di punti raccolti dagli utenti, il sistema funziona regolarmente, ma arrivati al checkout il vostro plugin invece modifica la cifra dello sconto, precedentemente inserito, con il valore dello scorporo dell'IVA dei prodotti presenti nel carrello. Sembra ci sia una sovrapposizione di campi, ovvero il vostro plugin sembra prendere il campo del coupon come se fosse il campo dell'IVA e cambia il suo valore prima di procedere con il pagamento. Potrebbe trattarsi di una sovrapposizione di nomi?

**Comment by LDAV** [comment]
il campo del coupon è un campo di WooCommerce. Non ci risulta esista un campo per l'IVA, e in ogni caso il plugin non interviene sull'eventuale esenzione.

**Comment by Carangelo** [comment]
Però disattivando il vostro plugin il carrello non viene ricalcolato ed il problema non si presenta. L'acquisto avviene poi regolarmente.
