### ISSUE TITLE
fattura con codice fiscale

### ISSUE THREAD

**Issue by toninolazzari** [LDAV/woocommerce-pdf-italian-add-on#2]
La normativa italiana permette di emettere fatture con codice fiscale anche senza p.iva cosa che ilnplugin non permette di fare. È possibile introdurre la possibilità

**Comment by LDAV** [comment]
Sì, certo. Stiamo cercando di raccogliere le tante richieste che stiamo ricevendo, tutte diverse e alle volte contrastanti, per preparare una versione che ne comprenda almeno una buona parte.
