### ISSUE TITLE
Campo azienda mancante

### ISSUE THREAD

**Issue by flax250** [LDAV/woocommerce-pdf-italian-add-on#20]
Ciao, da alcuni giorni è scomparso il campo "azienda" dal checkout.
Quale potrebbe essere il problema e come potrei risolverlo?

https://jersix.com/

Grazie mille.
Lorenzo

**Comment by LDAV** [comment]
Nella versione free del plugin non c'è nessuna "azienda". C'è nella versione Plus, a pagamento

**Comment by flax250** [comment]
Fino a pochi giorni fa sul sito compariva regolarmente il campo "azienda", è presente anche nel riepilogo degli ordini ricevuti in passato. 
Da un paio di giorni abbiamo notato la scomparsa di questo campo rendendo difficoltoso l'inserimento dei dati da parte dei clienti.

Sono stati effettuati aggiornamenti al plug-in recentemente che hanno limitato questa funzione?
