### ISSUE TITLE
Critical error with version: 0.8.8.3

### ISSUE THREAD

**Issue by moox-it** [LDAV/woocommerce-pdf-italian-add-on#29]
After upgrading to 0.8.8.3 Wordpress notify a critical error:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: WooCommerce_Italian_add_on_Settings_export::get_document_data(): Return value must be of type array, string returned in wp-content/plugins/woocommerce-italian-add-on/includes/class-wc-settings-export.php:216\n

Stack trace:\n#0 /wp-content/plugins/woocommerce-italian-add-on/includes/class-wc-settings-numerazione.php(418): WooCommerce_Italian_add_on_Settings_export->get_document_data()\n#1 wp-admin/includes/template.php(1456): WooCommerce_Italian_add_on_Settings_numerazione->meta_box_content()\n#2 wp-admin/edit-form-advanced.php(723): do_meta_boxes()\n#3 wp-admin/post.php(206): require('...')\n#4 {main}\n  thrown in wp-content/plugins/woocommerce-italian-add-on/includes/class-wc-settings-export.php on line 216',

**Comment by LDAV** [comment]
We have posted an update.
Thanks
