### ISSUE TITLE
Ultima release compatibile a partire da php 8

### ISSUE THREAD

**Issue by mike73rn** [LDAV/woocommerce-pdf-italian-add-on#30]
Nel file includes/class-wc-settings-export.php alla riga 153 il codice 
`public function get_document_data($order, $parent = null, $addnumber = 1): array|string {`
funziona solo a partire da php 8 e l'aggiornamento del plugin non verifica se il requisito è soddisfatto dal server.

**Comment by LDAV** [comment]
corretto.
