### ISSUE TITLE
Can't add manual order

### ISSUE THREAD

**Issue by AntoAGM** [LDAV/woocommerce-pdf-italian-add-on#5]
Hi,
I'm experiencing this issue adding a manual order:

Fatal error: Call to a member function get_meta() on boolean in ../public_html/wp-content/plugins/woocommerce-pdf-invoices-italian-add-on/includes/class-wcpdf-integration.php on line 24

![schermata-2017-07-13-alle-15 00 35](https://user-images.githubusercontent.com/4928963/28167560-489810d2-67dc-11e7-813a-aabd48fbe983.jpg)

How can I fix?

**Comment by LDAV** [comment]
see latest version of /includes/class-wcpdf-integration.php for test.
If it's work, as soon as possible will be included in a new release

**Comment by AntoAGM** [comment]
It works! Thanks!

Grazie ;)
