### ISSUE TITLE
Problema con download ricevuta dal my account

### ISSUE THREAD

**Issue by mattys81** [LDAV/woocommerce-pdf-italian-add-on#6]
Prima di tutto complimenti per l'ottimo plugin che avevo già avuto modo di testare altre 2 volte ed ho anche acquistato una versione pro:). Mi trovo ora con un sito però dove stranamente quando vado nella sezione my account (molto usata come ben sapete dai clienti), e voglio poter scaricare la ricevuta purtroppo il sistema non la scarica e da come errore "Non hai selezionato alcun ordine". Ho potuto constatare che a differenza della fattura che scarica tranquillamente nella ricevuta il link su browser ha un dato mancante. Manca il riferimento al numero ordine ids(come se il sistema non vedesse che è sull'ordine desiderato e per il quale si desidera fare il download della ricevuta. La stringa infatti è così composta. 

wp-admin/admin-ajax.php?action=generate_wpo_wcpdf&template_type=receipt&order_ids&my-account&_wpnonce=66c2f11145

Da backend invece si riesce a scaricare normalmente la ricevuta ed infatti è presente ids dell'ordine. Ho provato anche nuova installazione ma sempre questo errore mi da. Aspetto vs. risposta. Grazie mille anticipatamente e complimenti ancora per il plugin.

Mattia

**Comment by LDAV** [comment]
ciao Mattia
abbiamo fatto alcuni test e a noi il parametro ids viene indicato, e la ricevuta generata.
Riesci a produrre un debug.log per capire se c'è qualcos'altro?

**Comment by mattys81** [comment]
Se mi dite come fare il debug log ve lo produco subito! Non saprei però come poterlo fare:(. Lo si può fare da pannello wordpress? Grazie infinite!

**Comment by LDAV** [comment]
trovi le istruzioni qui:
https://codex.wordpress.org/it:Debug_in_WordPress

In pratica c'è da modificare una riga sul file /wp-config.php
da così:
`define('WP_DEBUG', false);`

a così:
`define('WP_DEBUG', true);`
`define('WP_DEBUG_LOG', true )`;
`define('WP_DEBUG_DISPLAY', false );`
`@ini_set( 'display_errors', 0 );`

Una volta fatto, apri la sezione My Admin del sito in questione e prova a scaricare la ricevuta.
Nella cartella /wp-content/, se ci sono errori, troverai un file "/wp-content/debug.log", che contiene gli eventuali errori nascosti da WordPress nella modalità _normale_.

Alla fine, riporta il file /wp-config.php alla situazione precedente.

**Comment by mattys81** [comment]
ecco l'errore che mi da:

[02-Nov-2017 10:58:34 UTC] PHP Notice:  Undefined variable: order_id in /web/htdocs/www.skikkerli.it/home/wp-content/plugins/woocommerce-pdf-invoices-italian-add-on/includes/class-wcpdf-integration2.php on line 202
[02-Nov-2017 10:58:34 UTC] PHP Notice:  Undefined variable: order_id in /web/htdocs/www.skikkerli.it/home/wp-content/plugins/woocommerce-pdf-invoices-italian-add-on/includes/class-wcpdf-integration2.php on line 202
[02-Nov-2017 10:58:34 UTC] PHP Notice:  Undefined variable: order_id in /web/htdocs/www.skikkerli.it/home/wp-content/plugins/woocommerce-pdf-invoices-italian-add-on/includes/class-wcpdf-integration2.php on line 202
[02-Nov-2017 10:58:34 UTC] PHP Notice:  Undefined variable: order_id in /web/htdocs/www.skikkerli.it/home/wp-content/plugins/woocommerce-pdf-invoices-italian-add-on/includes/class-wcpdf-integration2.php on line 202

**Comment by LDAV** [comment]
è un problema che avevamo già risolto
devi aggiornare il plugin all'ultima versione.

**Comment by mattys81** [comment]
Grazie mille di cuore!!! Aggiornato ora plugin e tutto è perfetto!! Grazie mille ancora per la vs. risposta velocissima e professionalità sempre top!

Mattia
