### ISSUE TITLE
dopo ultimo aggiornamento non invia ricevuta in allegato

### ISSUE THREAD

**Issue by MichelaF** [LDAV/woocommerce-pdf-italian-add-on#7]
Ciao, ho installato da poco il Vs grazioso plugin per cui Vi ringrazio molto.
Purtroppo dopo aver impostato l'emissione di ricevute per una associazione no profit per cui faccio volontariato, in seguito all'ultimo aggiornamento, la ricevuta non viene più spedita con l'email al completamento dell'ordine.
Potreste verificare?
Grazie mille
Mik

**Comment by LDAV** [comment]
ciao Michela
dovremmo aver risolto con la versione appena pubblicata su SVN e GitHub (0.5.1.1)
grazie della segnalazione.
