### ISSUE TITLE
wcpdf_IT_check_VatExpemptUE error

### ISSUE THREAD

**Issue by maremmano** [LDAV/woocommerce-pdf-italian-add-on#8]
Con le ultime versioni di: WP, WOO, WooCommerce PDF Invoices Italian Add-on

Ottengo errore sulla funzione: **wcpdf_IT_check_VatExpemptUE** 

Sembra che la funzione non sia definita all'interno di checkout.js

**Questo lo ottengo quando abilito l'esenzione IVA per:**
Applica l'esenzione IVA se il cliente è un'azienda o un professionista e il suo indirizzo estero di fatturazione è nella UE

**Comment by LDAV** [comment]
abbiamo corretto l'errore.
Si trattava di un'opzione che può riguardare solo la versione plus del plugin che non ha la ricevuta.
Grazie della segnalazione.
