### ISSUE TITLE
Fatture con Rimborso hanno importo errato

### ISSUE THREAD

**Issue by Luca4k4** [LDAV/woocommerce-pdf-italian-add-on#9]
Buonasera, 
utilizzo il vostro plugin già da un po', ultimamente mi è capitato di dover fare dei rimborsi prima di emettere fattura, tuttavia nonostante il rimborso risulta correttamente mostrato da Woocommerce, cliccando su "Crea PDF" -> "PDF Fattura" mi viene mostrata la fattura che non tiene in conto il rimborso.

Come posso risolvere? 

Grazie,
Luca

**Comment by LDAV** [comment]
ciao Luca4k4
il nostro plugin è un'integrazione di WooCommerce PDF Invoice & Packing Slips.
La versione premium di WooCommerce PDF Invoice & Packing Slips comprende nello specifico la gestione delle note di credito. In caso di rimborso la fattura viene sostituita da un altro documento.
